### ISSUE TITLE
3 issues in ASAN run

### ISSUE THREAD

**Issue by K2** [RoaringBitmap/CRoaring#281]
# all in test / bench code

We may want to tidy these up for guidance to consumers & to ensure possible underlying issues are not real.

## Read SEGV in run_container_benchmark
```bash
 number of values in container = 14498
run_container_to_uint32_array(out, Bt, 1234):  88.28 cycles per operation
run_container_contains run_cache_prefetch:  446.79 cycles per operation
run_container_contains run_cache_flush: AddressSanitizer:DEADLYSIGNAL
=================================================================
==188611==ERROR: AddressSanitizer: SEGV on unknown address 0x62f000020000 (pc 0x0000004c61b2 bp 0x7ffc4462e3c0 sp 0x7ffc4462e340 T0)
==188611==The signal is caused by a READ memory access.
    #0 0x4c61b2 in run_cache_flush /home/files/git/CRoaring/benchmarks/run_container_benchmark.c:16:9
    #1 0x4c96bc in main /home/files/git/CRoaring/benchmarks/run_container_benchmark.c:105:9
    #2 0x7fd3cd4c3cb1 in __libc_start_main csu/../csu/libc-start.c:314:16

```

##  Write SEGV add_benchmark

```bash
files@ZAMMEY:~/git/CRoaring/build/benchmarks$ ./add_benchmark
[cycles/element]
intvlen=1 density=0.200000 order=SHUFFLE
AddressSanitizer:DEADLYSIGNAL
=================================================================
==189318==ERROR: AddressSanitizer: SEGV on unknown address 0x00000000055c (pc 0x0000004ccc0c bp 0x7ffe6a7600f0 sp 0x7ffe6a75fa80 T0)
==189318==The signal is caused by a WRITE memory access.
==189318==Hint: address points to the zero page.
    #0 0x4ccc0c in run_test /home/files/git/CRoaring/benchmarks/add_benchmark.c:86:9
    #1 0x4cf4c7 in main /home/files/git/CRoaring/benchmarks/add_benchmark.c:171:13
    #2 0x7f32b8deccb1 in __libc_start_main csu/../csu/libc-start.c:314:16
    #3 0x4212dd in _start (/home/files/git/CRoaring/build/benchmarks/add_benchmark+0x4212dd)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/files/git/CRoaring/benchmarks/add_benchmark.c:86:9 in run_test
==189318==ABORTING
```

## Null pointer with zero offset used in mixed_container_unit

```bash
files@ZAMMEY:~/git/CRoaring/build/tests$ ./mixed_container_unit
[==========] Running 37 test(s).
[ RUN      ] array_bitset_and_or_xor_andnot_test
[       OK ] array_bitset_and_or_xor_andnot_test
[ RUN      ] array_bitset_run_lazy_xor_test
[       OK ] array_bitset_run_lazy_xor_test
[ RUN      ] run_xor_test
[       OK ] run_xor_test
[ RUN      ] run_ixor_test
[       OK ] run_ixor_test
[ RUN      ] run_andnot_test
[       OK ] run_andnot_test
[ RUN      ] run_iandnot_test
[       OK ] run_iandnot_test
[ RUN      ] run_array_andnot_bug_test
[       OK ] run_array_andnot_bug_test
[ RUN      ] array_bitset_ixor_test
[       OK ] array_bitset_ixor_test
[ RUN      ] array_bitset_iandnot_test
[       OK ] array_bitset_iandnot_test
[ RUN      ] array_negation_empty_test
/home/files/git/CRoaring/src/bitset_util.c:849:32: runtime error: applying zero offset to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/files/git/CRoaring/src/bitset_util.c:849:32 in
```

**Comment by lemire** [comment]
I am going to close this issue because we need to focus on real as opposed to potential issues. We run our tests using sanitizers. They are green. If you believe that your sanitized tests have revealed an actual issue, please investigate and identify it. Or better: submit a pull request. Unfortunately, all software has potential bugs. It is entirely likely that we have bugs remaining. However, it is not helpful to merely point that out. We need precise problems.

Let me state this again: we run all of our tests under sanitizers as a matter of policy. Every commit is tested under memory sanitizers.

It is entirely likely that it does not catch all bugs, but it is not helpful to be vague about it. Please narrow it down to specific bugs that we can fix.
