### ISSUE TITLE
Segmentation faults with roaring_bitmap_or and amalgamation

### ISSUE THREAD

**Issue by Ezibenroc** [RoaringBitmap/CRoaring#71]
This bug happens with my laptop (gcc 5.4.0, Linux 4.4.0, Ubuntu 16.04) and not with another PC (gcc 4.9.2, Linux 3.16.0, LMDE 2). I will try on another PC tomorrow.
This bug also happens with functions `roaring_bitmap_or_inplace`, `roaring_bitmap_xor` and `roaring_bitmap_xor_inplace`.
It only happens when the library is built using the amalgamation script. When cmake is used, everything is fine.

----

How to reproduce the bug:

File `bug.c`, in root directory of CRoaring:
```c
#include <roaring.h>

int main(int argc, char *argv[]) {

    uint32_t values1[] = {2,4,5,7,10,11,12,13,14,16,18,19,20,27,28};
    roaring_bitmap_t *bm1 = roaring_bitmap_of_ptr(sizeof(values1)/4, values1);
    roaring_bitmap_run_optimize(bm1);
    uint32_t values2[] = {45068,63618};
    roaring_bitmap_t *bm2 = roaring_bitmap_of_ptr(sizeof(values2)/4, values2);
    
    roaring_bitmap_t *result = roaring_bitmap_or(bm1, bm2);

    roaring_bitmap_free(bm1);
    roaring_bitmap_free(bm2);
    roaring_bitmap_free(result);

    return 0;
}
```

Then:
```bash
./amalgamation.sh
cc -g -O0 -march=native -std=c11 -shared -o libroaring.so -fPIC roaring.c
cc -g -O0 -fsanitize=address -Wall -o bug bug.c -lroaring -L . -I .
```

Error message:
```
ASAN:SIGSEGV
=================================================================
==28964==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fa2903d5b5e bp 0x7fff0d2139f0 sp 0x7fff0d213880 T0)
    #0 0x7fa2903d5b5d in _mm256_store_si256 /usr/lib/gcc/x86_64-linux-gnu/5/include/avxintrin.h:890
    #1 0x7fa2903d5b5d in run_container_cardinality /home/tom/CRoaring/roaring.c:137
    #2 0x7fa2903d962a in convert_run_to_efficient_container /home/tom/CRoaring/roaring.c:1667
    #3 0x7fa2903d97e4 in convert_run_to_efficient_container_and_free /home/tom/CRoaring/roaring.c:1711
    #4 0x7fa2903d3421 in container_or /home/tom/CRoaring/roaring.h:3655
    #5 0x7fa2903e5bac in roaring_bitmap_or /home/tom/CRoaring/roaring.c:6145
    #6 0x400ffc in main /home/tom/CRoaring/bug.c:14
    #7 0x7fa29001182f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #8 0x400af8 in _start (/home/tom/CRoaring/bug+0x400af8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /usr/lib/gcc/x86_64-linux-gnu/5/include/avxintrin.h:890 _mm256_store_si256
==28964==ABORTING
```

**Comment by lemire** [comment]
We need to look at this urgently.

**Comment by lemire** [comment]
I cannot reproduce this error. Here is my test configuration...

```
$ gcc --version
gcc (Ubuntu 5.4.1-2ubuntu1~16.04) 5.4.1 20160904
$ uname -a
Linux skylake 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Note that line numbers do not appear to match what we have in master...

```
$ git pull
Already up-to-date.
$ git diff
$ ./amalgamation.sh
$ grep -n "int run_container_cardinality" roaring.c
5623:int run_container_cardinality(const run_container_t *run) {
5654:int run_container_cardinality(const run_container_t *run) {
$ grep -n "*convert_run_to_efficient_container" roaring.c
3554:void *convert_run_to_efficient_container(run_container_t *c,
3603:void *convert_run_to_efficient_container_and_free(run_container_t *c,
```

I'm issuing a new release. Right now. Please verify against the release, making sure that you are using the same code as I am.

**Comment by lemire** [comment]
I think I figured it out. I can't reproduce your exact bug, but the problem is _mm256_store_si256 which can be unsafe if the memory is not aligned.

**Comment by lemire** [comment]
Ok. The issue should be fixed with version 0.2.11, just issued. Please upgrade. Reopen if the bug persists.

**Comment by Ezibenroc** [comment]
I confirm that the issue has been fixed, thanks!

**Comment by lemire** [comment]
Thanks for reporting it!
